version: '3'
services:
  ztdns:
    build: .
    ports:
     - "5356:53/udp"
    environment:
      - ZT_API
      - ZT_URL
      - ZT_DOMAIN
      - ZT_NETWORK
      - ZTDNS_SUFFIX
      - ZTDNS_PORT
      - ZTDNS_INTERFACE
      - ZTDNS_DBREFRESH

