apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ztdns.fullname" . }}
  labels:
    {{- include "ztdns.labels" . | nindent 4 }}
data:
  # Configuration is provided via environment variables. Set the following in your deployment:
  # ZTDNS_SUFFIX, ZTDNS_PORT, ZTDNS_INTERFACE, ZTDNS_DBREFRESH, ZTDNS_ZT_URL, ZTDNS_ZT_API, ZTDNS_NETWORKS
  # Example (in Helm values/templates):
  # env:
  # - name: ZTDNS_ZT_API
  #   value: "{{ .Values.zerotier.api }}"
  # - name: ZTDNS_ZT_URL
  #   value: "{{ .Values.zerotier.url }}"


