apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ztdns.fullname" . }}
  labels:
    {{- include "ztdns.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ztdns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ztdns.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "server"
          env:
            - name: ZTDNS_ZT_API
              {{- if .Values.secrets.useSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "ztdns.fullname" . }}
                  key: {{ default "ZEROTIER_TOKEN" .Values.secrets.tokenKey }}
              {{- else }}
              value: "{{ .Values.zerotier.apiToken }}"
              {{- end }}
            - name: ZTDNS_ZT_URL
              value: "{{ .Values.zerotier.url }}"
            - name: ZTDNS_SUFFIX
              value: "{{ .Values.zerotier.suffix }}"
            - name: ZTDNS_PORT
              value: "{{ .Values.zerotier.port }}"
            - name: ZTDNS_INTERFACE
              value: "{{ .Values.zerotier.interface }}"
            - name: ZTDNS_DBREFRESH
              value: "{{ .Values.zerotier.dbRefresh }}"
            - name: ZTDNS_NETWORKS
              value: "{{- $pairs := list -}}{{- range .Values.zerotier.networks -}}{{- $pairs = append $pairs (printf "%s=%s" .domain .networkId) -}}{{- end -}}{{- join "," $pairs -}}"
          ports:
            - name: dns
              containerPort: {{ .Values.zerotier.port }}
              protocol: UDP
          livenessProbe:
            exec:
              command:
                - "nc"
                - "-z"
                - "-v"
                - "-u"
                - "127.0.0.1"
                - "{{ .Values.zerotier.port }}"
          readinessProbe:
            exec:
              command:
                - "nc"
                - "-z"
                - "-v"
                - "-u"
                - "127.0.0.1"
                - "{{ .Values.zerotier.port }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

